directories:
  work_directory: "/lila/data/kentsis/testfiles/K052_sub/"
  temporary_directory: "/scratch/chenz4/"
references:
  fasta: "/lila/home/chenz4/proteomegenerator/K052_test_genome.fa"
  snp: "/lila/data/kentsis/Databases/resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf"
  indel: "/lila/data/kentsis/Databases/resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz"
fastq:
  one: "/lila/home/chenz4/proteomegenerator/K052_DNA_subset_r1.fastq"
  two: "/lila/home/chenz4/proteomegenerator/K052_DNA_subset_r2.fastq"
readgroup:
  id: "K052"
  sample: "K052_tumor"
  library: "Library"
  platform: "ILLUMINA"
  sequencing_center: "MSK"
  run_date: "2018-07-27"
