directories:
  work_directory: "/lila/data/kentsis/testfiles/pgm2_test/"
  temporary_directory: "/scratch/chenz4"
references:
  fasta: "/lila/data/kentsis/Databases/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta"
  snp: "/lila/data/kentsis/Databases/resources_broad_hg38_v0_Homo_sapiens_assembly38.dbsnp138.vcf"
  indel: "/lila/data/kentsis/Databases/resources_broad_hg38_v0_Homo_sapiens_assembly38.known_indels.vcf.gz"
  gtf: "doesn'texist.gtf"
  index: "/data/poirier/indexes/GRCh38/STAR"
  uniprot: "/data/poirier/indexes/uniprot/UP000005640.fasta"
preprocess:
  fastq1: "/lila/home/chenz4/proteomegenerator/K052_DNA_subset_r1.fastq"
  fastq2: "/lila/home/chenz4/proteomegenerator/K052_DNA_subset_r2.fastq"
readgroup:
  id: "K052"
  sample: "K052_tumor"
  library: "Library"
  platform: "ILLUMINA"
  sequencing_center: "MSK"
  run_date: "2018-07-27"
variant:
  normal:
    file: "/lila/data/kentsis/testfiles/K052M2_test/out/preprocess/normal.bam"
    name: "K052_normal"
rna:
  name: "FCH9EFLADXX-HUMbghEAACRAAPEI-225"
  read_one:
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L1_1.fq.gz"
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L2_1.fq.gz"
  read_two:
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L1_2.fq.gz"
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L2_2.fq.gz"
maxquant:
  raw_directory: "/lila/data/kentsis/testfiles/K056PGPar"
  threads: "30"
