directories:
  work_directory: "/lila/data/kentsis/testfiles/K0562_newtest/"
  temporary_directory: "/scratch/chenz4"
references:
  fasta: "/data/poirier/indexes/GRCh38/GRCh38.genome.fa"
  gtf: "/data/poirier/indexes/GRCh38/gencode.v20.annotation.gtf"
  index: "/data/poirier/indexes/GRCh38/STAR"
  uniprot: "/data/poirier/indexes/uniprot/UP000005640.fasta"
samples:
  name: "FCH9EFLADXX-HUMbghEAACRAAPEI-225"
  read_one:
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L1_1.fq.gz"
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L2_1.fq.gz"
  read_two:
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L1_2.fq.gz"
    - "/lila/data/kentsis/RNAseq/K0562/FCH9EFLADXX-HUMbghEAACRAAPEI-225_L2_2.fq.gz"
maxquant:
  raw_directory: "/lila/data/kentsis/testfiles/K056PGPar"
  threads: "30"