directories:
  work_directory: "/lila/data/kentsis/testfiles/K052_sub/"
  temporary_directory: "/scratch/chenz4/"
references:
  fasta: "/lila/home/chenz4/proteomegenerator/testfiles/K052_test_genome.fa"
  gtf: "/data/poirier/indexes/GRCh38/gencode.v20.annotation.gtf"
samples:
  tumor:
    file: "/lila/home/chenz4/proteomegenerator/testfiles/K052_test.bam"
    name: "K052_tumor"
  normal:
    file: "/lila/data/kentsis/testfiles/K052M2_test/out/preprocess/normal.bam"
    name: "K052_normal"
